# Generated by Django 4.2.15 on 2024-08-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('product_descrition', models.CharField(default='', max_length=100)),
                ('product_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
